// Objective-C API for talking to github.com/metacubex/mihomo/mobile Go package.
//   gobind -lang=objc github.com/metacubex/mihomo/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileTunOptions;
@protocol MobileSocketProtector;
@class MobileSocketProtector;
@protocol MobileTunOpener;
@class MobileTunOpener;

@protocol MobileSocketProtector <NSObject>
- (BOOL)markSocket:(int64_t)fd network:(NSString* _Nullable)network address:(NSString* _Nullable)address;
- (BOOL)protectSocket:(int64_t)fd network:(NSString* _Nullable)network address:(NSString* _Nullable)address;
@end

@protocol MobileTunOpener <NSObject>
- (int64_t)openTun:(MobileTunOptions* _Nullable)options;
@end

@interface MobileTunOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)autoRoute;
- (NSString* _Nonnull)dnsHijack;
- (NSString* _Nonnull)dnsServers;
- (BOOL)disableICMPForwarding;
- (NSString* _Nonnull)excludeInterface;
- (NSString* _Nonnull)includeInterface;
- (NSString* _Nonnull)inet4Address;
- (NSString* _Nonnull)inet6Address;
- (NSString* _Nonnull)json;
- (int64_t)mtu;
- (NSString* _Nonnull)name;
- (NSString* _Nonnull)routeAddress;
- (NSString* _Nonnull)routeExcludeAddress;
- (NSString* _Nonnull)stack;
- (BOOL)strictRoute;
@end

FOUNDATION_EXPORT void MobileClearSocketProtector(void);

FOUNDATION_EXPORT void MobileClearTunOpener(void);

FOUNDATION_EXPORT void MobileForceUpdateConfig(NSString* _Nullable configFileName);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetMode(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetProxies(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileProxyNames(void);

FOUNDATION_EXPORT BOOL MobileSelectProxy(NSString* _Nullable groupName, NSString* _Nullable proxyName);

FOUNDATION_EXPORT void MobileSetLogLevel(NSString* _Nullable level);

/**
 * SetMode sets the running mode.
mode: rule, global, direct
 */
FOUNDATION_EXPORT void MobileSetMode(NSString* _Nullable mode);

FOUNDATION_EXPORT void MobileSetSocketProtector(id<MobileSocketProtector> _Nullable protector);

FOUNDATION_EXPORT void MobileSetTunOpener(id<MobileTunOpener> _Nullable opener);

FOUNDATION_EXPORT void MobileStart(NSString* _Nullable home, NSString* _Nullable configFileName);

FOUNDATION_EXPORT void MobileStop(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileTestLatency(NSString* _Nullable proxyName);

FOUNDATION_EXPORT int64_t MobileTrafficDown(void);

FOUNDATION_EXPORT int64_t MobileTrafficTotalDown(void);

FOUNDATION_EXPORT int64_t MobileTrafficTotalUp(void);

FOUNDATION_EXPORT int64_t MobileTrafficUp(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileVersion(void);

@class MobileSocketProtector;

@class MobileTunOpener;

@interface MobileSocketProtector : NSObject <goSeqRefInterface, MobileSocketProtector> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)markSocket:(int64_t)fd network:(NSString* _Nullable)network address:(NSString* _Nullable)address;
- (BOOL)protectSocket:(int64_t)fd network:(NSString* _Nullable)network address:(NSString* _Nullable)address;
@end

@interface MobileTunOpener : NSObject <goSeqRefInterface, MobileTunOpener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (int64_t)openTun:(MobileTunOptions* _Nullable)options;
@end

#endif
